export const ErrorCodes: Record<number, string> = {
  3000: 'API key not found. Make sure the "AH-BOHUDUR-API-KEY" header is included in the request.',
  3001: 'Required parameters not found. "name", "email", "amount", "returnType", "redirectURL", and "cancelURL" are all required.',
  3002: 'One or more required parameters are empty. "name", "email", "amount", "returnType", "redirectURL", and "cancelURL" must all have non-empty values.',
  3003: 'Invalid "name" format. It must be a valid non-empty string.',
  3004: 'Invalid "email" format. Provide a valid email address.',
  3005: 'Invalid "amount" format. It must be a positive numeric value.',
  3006: 'Invalid "returnType" format. Only "GET" or "POST" is allowed.',
  3007: 'Invalid "redirectURL" format. Provide a valid URL, or "default" to use Bohudur\'s default page.',
  3008: 'Invalid "cancelURL" format. Provide a valid URL, or "default" to use Bohudur\'s default page.',
  3009: 'Invalid JSON format in "metadata". It must be a valid JSON object.',
  3010: 'Invalid JSON format in "webhook". It must form a valid webhook object.',
  3011: 'Invalid webhook actions. Only "success" and "cancel" are allowed.',
  3012: 'Invalid JSON format in "metadata" or "webhook". One or both are malformed.',
  3013: "Invalid API key. The provided key is incorrect or inactive.",
  3014: "Oops! Internal error. Try again.",
  3015: 'Unknown amount provided. The "amount" value is not acceptable.',
  3016: "You don't have access. This request was blocked due to an IP restriction.",
  3017: "Oops! Internal error. Try again.",
  3018: "Unable to create payment. The payment session could not be created.",
  3050: 'API key not found. Make sure the "AH-BOHUDUR-API-KEY" header is included in the request.',
  3051: "API key not valid. The provided key is invalid or inactive.",
  3052: 'Invalid "paykey". It does not exist or is malformed.',
  3053: "Invalid API key. It does not match any active account.",
  3054: "You don't have access. Your server's IP is not authorized.",
  3055: 'Payment data not found. No payment exists for this "paykey".',
  3100: 'API key not found. Make sure the "AH-BOHUDUR-API-KEY" header is included in the request.',
  3101: "API key not valid. The provided key is invalid or inactive.",
  3102: 'Invalid "paykey". It is malformed or does not exist.',
  3103: "Invalid API key. It does not match any active account.",
  3104: "You don't have access. Your server's IP is not authorized.",
  3105: 'Payment data not found. No payment exists for this "paykey".',
  3106: "Payment is pending. The customer has not completed payment yet.",
  3107: "Payment is cancelled. Cancelled payments cannot be executed.",
  3108: "Payment already executed. This payment was already executed once and cannot be executed again.",
  3109: "Failed to execute payment due to a server or processing error."
}
